# Generated by Django 2.2.24 on 2021-08-12 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0002_auto_20210811_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ngo_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='payment_for',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
